spring.application.name=SpringbootSession
management.endpoints.web.exposure.include = *
management.info.env.enabled=true

management.endpoints.web.exposure.exclude = health,info


info.app.name = Actuator Session
info.app.description = A great fun session of actuator
info.app.version = 1.0.0


coach.name = "Zahab"
team.name = "Payments"

server.port = 2939
server.servlet.context-path = /MyApp


spring.security.user.name = admin
spring.security.user.password = admin
